version: '3.8'
services:
  mysql:
    image: mysql:8.0.20
    ports:
      - "8002:3306"
    volumes:
      - mysql_vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Rails-Docker
    ports:
      - "3000:3000"
    depends_on:
      - mysql
volumes:
  mysql_vol: